version: "3.8"

# TODO: make custom docker images
services:
  api:
    build: .
    restart: always
    ports:
      - 443:8000
    command: bash -c "alembic upgrade head && uvicorn app.main:api --proxy-headers --host 0.0.0.0 --ssl-keyfile app/core/certificates/star_kieback-peter.net-decrypted.key --ssl-certfile app/core/certificates/star_kieback-peter.net.crt --reload"
    environment:
      - API_LOG_LEVEL=${API_LOG_LEVEL}
      - SIGN_KEY=${SECRET_API_KEY}
      - TOKEN_EXPIRE_MINUTES=${TOKEN_EXPIRE_MINUTES}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
    volumes:
      - ./app:/code/app
    depends_on:
      - database
      - worker

  worker:
    build: .
    command: celery -A app.energy.worker.celery worker --loglevel=info
    volumes:
      - ./worker:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_RESULT_BACKEND=redis://broker:6379/0
    depends_on:
      - broker
      - database

  flower:
    build: .
    command: celery --broker=redis://broker:6379/0 flower --port=5555
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=redis://broker:6379/0
      - CELERY_RESULT_BACKEND=redis://broker:6379/0
    depends_on:
      - worker

  broker:
    image: redis:7

  database:
    image: postgres
    restart: always
    ports:
      - ${DB_PORT} # append :5432 for forwarding to localhost
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - energy-database:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    environment:
      - PGADMIN_DEFAULT_SERVER=${DB_HOST}
      - PGADMIN_DEFAULT_EMAIL=admin@kieback-peter.nl
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - database

volumes:
  energy-database:
  pgadmin-data:
